name: yim
description: Yanhx IM

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  shared_preferences: ^0.5.6+3
  json_annotation: ^2.0.0
  fluttertoast: ^4.0.1
  dio: ^3.0.9
  protobuf: ^1.0.1
  pull_to_refresh: ^1.5.7
  bubble: ^1.1.9+1
  photo_view: ^0.9.2
  audioplayers: ^0.14.2
  video_player: ^0.10.8+1
  video_thumbnail: ^0.2.0
  path_provider: ^1.6.5
  image_picker: ^0.6.4
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
